[package]
name = "counter"
version = "0.1.0"
publish = false
edition = "2024"


[dependencies]
state_machine_games = {path = "../../state_machine_games", features = ["leptos"]}
console_error_panic_hook = {workspace=true}
wasm-logger = {workspace=true}
leptos = { workspace=true, features = ["csr"] }
glam = {workspace=true}
tiny_graph = {git = "https://github.com/wainwrightmark/tiny_graph"}
rand_core = {workspace=true}
rand = {workspace=true}

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.3", features = ["wasm_js"] }

[dev-dependencies]
insta   = "1.43"
test-case= "3"
