[package]
name = "quiz_salad"
version = "0.1.0"
publish = false
edition = "2024"


[dependencies]
state_machine_games = {path = "../../state_machine_games"}
geometrid = "0.10"
wasm-logger = "0.2.0"
console_error_panic_hook = "0.1.7"
rand= "0.9"
web-time = "1.1"
serde = { version = "1", features = ["derive", "rc"] }
strum = { version = "0.27", features = ["derive"] }
itertools = {version = "0.14"}
ws_core = {path = 'C:\Source\rust\word_salad\ws_core'}
anyhow = "1"


leptos = { version = "0.8", features = ["csr"] }
leptos-use = {version = "0.16"}
const_sized_bit_set = "0.3.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.3", features = ["wasm_js"] }

[dev-dependencies]
insta   = "1.43"
test-case= "3"