[package]
name = "state_machine_games"
version = "0.1.0"
edition = "2024"

[dependencies]
console_error_panic_hook = {workspace = true }
wasm-logger = {workspace = true }
leptos = { workspace = true , features = ["csr"], optional = true}
glam = {workspace = true }

leptos-use = {workspace = true, optional = true}
rand = {workspace = true }
static_assertions = {workspace = true }
impl-trait-for-tuples = {workspace = true }
strum = { workspace = true, features = ["derive"] }
const_sized_bit_set = {workspace = true, features = ["std"]}
bevy_color = {workspace = true, optional = true}

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.3", features = ["wasm_js"] }


[dev-dependencies]
insta = {workspace = true }

[features]
leptos = ["dep:leptos", "dep:leptos-use"]
bevy_color= ["dep:bevy_color"]
